# Generated by Django 5.2.6 on 2025-10-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(choices=[('GENERAL', 'general'), ('ARCHITECTURAL', 'architectural'), ('STRUCTURAL', 'structural'), ('ELECTRICAL', 'electrical'), ('PLUMBING', 'plumbing'), ('HVAC', 'hvac')], max_length=100),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(choices=[('GENERAL', 'general'), ('ARCHITECTURAL', 'architectural'), ('STRUCTURAL', 'structural'), ('ELECTRICAL', 'electrical'), ('PLUMBING', 'plumbing'), ('HVAC', 'hvac')], max_length=200)),
                ('issue_title', models.CharField(max_length=100)),
                ('detailed_description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=100)),
                ('assigned_to', models.CharField(choices=[('GENERAL', 'general'), ('ARCHITECTURAL', 'architectural'), ('STRUCTURAL', 'structural'), ('ELECTRICAL', 'electrical'), ('PLUMBING', 'plumbing'), ('HVAC', 'hvac')], max_length=100)),
                ('due_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue')),
            ],
        ),
    ]
