# Generated by Django 5.2.6 on 2025-10-17 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='trades',
        ),
        migrations.AddField(
            model_name='trade',
            name='subcontractors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'SUB CONTRACTOR'}, related_name='specialized_trades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUB CONTRACTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=50),
        ),
    ]
