# Generated by Django 5.2.6 on 2025-10-17 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_trades_trade_subcontractors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='subcontractors',
        ),
        migrations.AddField(
            model_name='project',
            name='trades',
            field=models.ManyToManyField(to='core.trade'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='open', max_length=50),
        ),
    ]
