# Generated by Django 5.2.6 on 2025-10-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_trade_subcontractors_project_trades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trade'),
        ),
    ]
