# Generated by Django 5.2.6 on 2025-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_issue_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(choices=[('GENERAL', 'general'), ('ARCHITECTURAL', 'architectural'), ('STRUCTURAL', 'structural'), ('ELECTRICAL', 'electrical'), ('PLUMBING', 'plumbing'), ('HVAC', 'hvac')], max_length=100, unique=True),
        ),
    ]
